package org.rationalityfrontline.ktrader.broker.api

import java.time.LocalDate
import java.time.LocalDateTime

data class Tick(
    val code: String,
    val time: LocalDateTime,
    val lastPrice: Double,
    val bidPrice: Array<Double>,
    val askPrice: Array<Double>,
    val bidVolume: Array<Int>,
    val askVolume: Array<Int>,
    val volume: Int,
    val turnover: Double,
    val openInterest: Int,
    val direction: TickDirection,
    var status: MarketStatus,
    val yesterdayClose: Double,
    val yesterdaySettlementPrice: Double,
    val yesterdayOpenInterest: Int,
    val todayOpenPrice: Double,
    val todayClosePrice: Double,
    val todayHighPrice: Double,
    val todayLowPrice: Double,
    val todayHighLimitPrice: Double,
    val todayLowLimitPrice: Double,
    val todaySettlementPrice: Double,
    val todayAvgPrice: Double,
    val todayVolume: Int,
    val todayTurnover: Double,
    val todayOpenInterest: Int,
    var extras: MutableMap<String, Any>? = null,
)

data class Order(
    val accountId: String,
    val orderId: String,
    val code: String,
    val price: Double,
    val volume: Int,
    val direction: Direction,
    val offset: OrderOffset,
    val orderType: OrderType,
    var status: OrderStatus,
    var statusMsg: String,
    var filledVolume: Int,
    var turnover: Double,
    var avgFillPrice: Double,
    var frozenCash: Double,
    var commission: Double,
    val createTime: LocalDateTime,
    var updateTime: LocalDateTime,
    var extras: MutableMap<String, Any>? = null,
)

data class Trade(
    val accountId: String,
    val tradeId: String,
    val orderId: String,
    val code: String,
    val price: Double,
    val volume: Int,
    var turnover: Double,
    val direction: Direction,
    var offset: OrderOffset,
    var commission: Double,
    val time: LocalDateTime,
    var extras: MutableMap<String, Any>? = null,
)

data class MarginRate(
    val code: String,
    val longMarginRatioByMoney: Double,
    val longMarginRatioByVolume: Double,
    val shortMarginRatioByMoney: Double,
    val shortMarginRatioByVolume: Double,
    var extras: MutableMap<String, Any>? = null,
)

data class CommissionRate(
    val code: String,
    val openRatioByMoney: Double,
    val openRatioByVolume: Double,
    val closeRatioByMoney: Double,
    val closeRatioByVolume: Double,
    val closeTodayRatioByMoney: Double,
    val closeTodayRatioByVolume: Double,
    var orderInsertFeeByVolume: Double = 0.0,
    var orderCancelFeeByVolume: Double = 0.0,
    var orderInsertFeeByTrade: Double = 0.0,
    var orderCancelFeeByTrade: Double = 0.0,
    val optionsStrikeRationByMoney: Double = 0.0,
    val optionsStrikeRationByVolume: Double = 0.0,
    var extras: MutableMap<String, Any>? = null,
)

data class Instrument(
    val code: String,
    val type: InstrumentType,
    val productId: String = "",
    val name: String,
    val priceTick: Double,
    val isTrading: Boolean,
    val openDate: LocalDate,
    val expireDate: LocalDate? = null,
    val endDeliveryDate: LocalDate? = null,
    val volumeMultiple: Int = 1,
    val isUseMaxMarginSideAlgorithm: Boolean = false,
    var marginRate: MarginRate? = null,
    var commissionRate: CommissionRate? = null,
    val optionsType: OptionsType? = null,
    val optionsUnderlyingCode: String = "",
    val optionsStrikePrice: Double = 0.0,
    var extras: MutableMap<String, Any>? = null,
)

data class Assets(
    val accountId: String,
    var total: Double,
    var available: Double,
    var positionValue: Double,
    var frozenByOrder: Double,
    var todayCommission: Double,
    var extras: MutableMap<String, Any>? = null,
)

data class Position(
    val accountId: String,
    val code: String,
    val direction: Direction,
    var yesterdayVolume: Int,
    var volume: Int,
    var value: Double,
    var todayVolume: Int,
    var frozenVolume: Int,
    var closeableVolume: Int,
    var todayOpenVolume: Int,
    var todayCloseVolume: Int,
    var todayCommission: Double,
    var openCost: Double,
    var avgOpenPrice: Double,
    var lastPrice: Double,
    var pnl: Double,
    var extras: MutableMap<String, Any>? = null,
)